### ISSUE TITLE
Support post-split RewriteHost

### ISSUE THREAD

**Issue by mattmoor** [knative/networking#109]
In order to target ExternalName services that rely on Host-based dispatch (the way we do for ksvc), we essentially need to support rewriting every service reference to it's internal hostname in order for it to correctly receive traffic.

We can work around this today for the trivial vanity domain case because we can put the RewriteHost pre-split, since there's a single split, however, if we wanted to correctly traffic split over two ksvc with kingress, then we could not do that with the kingress we have today.

cc @julz @tcnghia 

Related: https://github.com/knative/networking/pull/107
This would need some extension: https://github.com/knative-sandbox/net-contour/pull/220

**Comment by nak3** [comment]
I assumed that ingress v2 could solve the issue but it was not so simple.
I opened https://github.com/projectcontour/contour/issues/3565 and learned it is not possible for Contour to rewrite host in post-split (=per-service configuration).

Contour doc also mentioned it - https://projectcontour.io/docs/v1.14.0/config/api/#projectcontour.io/v1.Service
> Rewriting the ‘Host’ header is not supported.
