### ISSUE TITLE
Annotation validation for networking.knative.dev

### ISSUE THREAD

**Issue by arturenault** [knative/networking#123]
/kind good-first-issue

Currently we validate that users can't create resources with annotations with the `serving.knative.dev` prefix in the [`validateKnativeAnnotations`](https://github.com/knative/serving/blob/master/pkg/apis/serving/metadata_validation.go#L57). We currently don't appear to have any such validation for the `networking.knative.dev` prefix.

I see two useful things to get out of this:
- We can create a file similar to [annotation_validation in autoscaler](https://github.com/knative/serving/blob/master/pkg/apis/autoscaling/annotation_validation.go), which performs validation on all the annotations owned by autoscaler, including validating the values of the annotations themselves.
- We could modify the `validateKnativeAnnotations` to validate all annotation prefixes owned by knative. I suspect this gap exists for other annotation groups as well.

Moved from knative/serving#9192

**Comment by MIBc** [comment]
Every annotation start with networking.knative.dev is forbidden for users?

**Comment by vagababov** [comment]
Users cannot create their own annotations with such prefix.

**Comment by arghya88** [comment]
I see already `GroupName = "networking.internal.knative.dev"` in code. Should we validate annotation on this group or we need something like

```
// GroupName is the name for the internal networking API group.
	InternalGroupName = "networking.internal.knative.dev"
// GroupName is the name for the networking API group.
	GroupName = "networking.knative.dev"
```

And then validate on `GroupName`

**Comment by arturenault** [comment]
We should validate on both, ideally.
