### ISSUE TITLE
Move network.yaml from serving repo to networking repo

### ISSUE THREAD

**Issue by ZhiminXiang** [knative/networking#141]
As networking repo is specific to host networking resources, it makes sense to move the [network.yaml](https://github.com/knative/serving/blob/master/config/core/configmaps/network.yaml) from serving repo to networking repo.

/cc @tcnghia @nak3

**Comment by nak3** [comment]
Yes, @tcnghia is working on this in https://github.com/knative/networking/pull/57

**Comment by tcnghia** [comment]
This is fixed by #57
