### ISSUE TITLE
"--enable-alpha" option must implement all alpha features

### ISSUE THREAD

**Issue by nak3** [knative/networking#183]
When we use `--enable-alpha` flag, all alpha tests are included.
For example in the current alpha tests:

https://github.com/knative/networking/blob/6ae03526c394d2487039e3cad36111682dce99a5/test/conformance/ingress/run.go#L71-L75

we want to run `TestTagHeaders` but we did not implement `TestRewriteHost` yet. In this case, we need to give up both tests to run.

**Comment by nak3** [comment]
cc @dprotaso  @mattmoor

We got some feedback like https://github.com/knative-sandbox/net-kourier/pull/158#issuecomment-697295459 or https://github.com/knative-sandbox/net-kourier/pull/158#issuecomment-697303490

**Comment by dprotaso** [comment]
If you want to run a subset of tests you’ll have to use the `go test -run [regex]`

**Comment by nak3** [comment]
@dprotaso It is possible but we need to use multiple go test invocations as you commented it in https://github.com/knative-sandbox/net-kourier/pull/158#issuecomment-697318978.
Additionally, if we added more Alpha features e.g. `TestFoo`, we need to three times to run the tests - 1). to run all tests except alpha features, 2) to run `—enable-alpha -run TestTagHeaders` 3) to run `—enable-alpha -run TestFoo`, right?

Is it not good idea to support `skip-tests` option like https://github.com/knative/networking/pull/184 ?

**Comment by dprotaso** [comment]
you could use one invocation with right regex
