### ISSUE TITLE
Cleanup test flags naming

### ISSUE THREAD

**Issue by tcnghia** [knative/networking#214]
We have 3 kinds of flag names:

- resolvabledomain -> ResolvableDomain
- enable-alpha -> enableAlpha
- ingressClass -> ingressClass

Would be nice to use same style, so test writers don't have to be confused about which way is right.

**Comment by vagababov** [comment]
Note that those are doubles and are imported in serving. I am not sure you can do this without a failure downstream.

**Comment by nak3** [comment]
Yeah, I noticed that serving has the same flag https://github.com/knative/serving/blob/8b121ccf3ec59043c42bd3853157598a7362cd44/test/e2e_flags.go#L106-L122

**Comment by tcnghia** [comment]
@vagababov I think you can:
- [ ] duplicate all the flags (i.e. having both `ingressClass` and `ingress-class` pointing to same pointer)
- [ ] update downstream
- [ ] undup

**Comment by vagababov** [comment]
I already made sure we can work with duplicate flags :-)
But thing is if you dedup them you'll also need to change test scripts.
I.e. is this even worth it?
