### ISSUE TITLE
Establish cherry-pick policy for net-* CRDs

### ISSUE THREAD

**Issue by tcnghia** [knative/networking#238]
@houshengbo brought it up that it would make things easier for the Knative operator to upgrade KIngress if patch releases don't change the CRDs (add/remove/rename).

Generally, these kinds of cherrypicks are riskier so we don't have many like that. However, it would be good to establish a guideline about cherrypicks to make things easier for the operator.

cc @nak3 @ZhiminXiang @mattmoor @dprotaso @houshengbo

**Comment by mattmoor** [comment]
Do you have an example of such a change (CP or otherwise)?

**Comment by tcnghia** [comment]
This is one example of such a change https://github.com/knative-sandbox/net-istio/pull/237/files (adding resources).

**Comment by mattmoor** [comment]
I think my $0.02 is that we shouldn't limit the facilities available to us to fix things in a patch release, but we should be extremely judicious in rejecting CPs that aren't critical fixes or have reasonable workarounds.

Suppose we are missing a necessary role binding for a supported scenario we've under-tested?  We can try to be creative in how we fix things to avoid it, but I don't want to artificially tie our hands wrt getting a fix out.

WRT rejecting patches upstream...  folks can always carry additional patches downstream if they want to "backport" a fix further.  This is necessary for EOL releases anyways, which some vendors may choose to continue supporting.


I'd probably reject the above patch as a CP on the grounds that it isn't a fix.
