### ISSUE TITLE
Document compatibility of knative/serving and knative/net-* versions

### ISSUE THREAD

**Issue by tcnghia** [knative/networking#239]
Since we follow the 6-month deprecation policy, any knative/serving version should work with a net-xxx version released 6 months ago, i.e. backward compatibility.

However, I am not sure we have any guarantee the other way around. Since we only get testing of knative/serving version 0.X.y with knative-sandbox/net-* version 0.X.z, the only forward compatibility is just with patch versions.

I'd love to see some confirmation from @nak3 @ZhiminXiang @mattmoor about this, following by some documentations.

Thanks @houshengbo who raised this very interesting question.

**Comment by nak3** [comment]
Although we don't test the forward compatibility, I don't see any problem and it would be worth to support.
That allows users to upgrade Istio version with only the compatible net-istio plugin without Serving upgrade.

For backward compatibility, yes we can support it for 6 months.
