### ISSUE TITLE
[HTTP Option support] HTTP Option for Kingress design

### ISSUE THREAD

**Issue by ZhiminXiang** [knative/networking#257]
For the auto TLS feature, we want to support httpProtocol https://github.com/knative/networking/blob/master/config/config-network.yaml#L106.

Currently this feature is only supported by net-istio as net-istio directly consumes the value of config-network configmap. We should instead add the httpProtocol into Kingress spec so that the rest of kingress implementations could follow the conformance and support it.

**Comment by nak3** [comment]
Link to proposal doc https://docs.google.com/document/d/1yVOGo-j1hI7oCpuWVIi5iBJwX1wKbOzWaV0QNJxCbaY/

**Comment by ZhiminXiang** [comment]
Marked this issue as done as the design is finished. Will break it into smaller actionable items.
