### ISSUE TITLE
[HTTP Option support] Add HTTPOption into Kingress spec

### ISSUE THREAD

**Issue by ZhiminXiang** [knative/networking#297]
This is the first part of the httpOption support work. We need to add httpOption into Kingress spec.

Full design: https://docs.google.com/document/d/1yVOGo-j1hI7oCpuWVIi5iBJwX1wKbOzWaV0QNJxCbaY

**Comment by arghya88** [comment]
@ZhiminXiang so how do we take this forward? What was the issue with previous PR?

**Comment by ZhiminXiang** [comment]
@arghya88 sorry for not making it clear in the code review of the previous PR.

So there are several issues:
1. We should not add the default value for httpOption (i.e. this [section](https://github.com/knative/networking/pull/306/files#diff-7d929c762da1c43abbb54914788435726667271c2e81d6d45e85f27674259aacR38)) as it will break the downgrade (i.e. the httpOption cannot be parsed after downgrading knative networking as the downgraded version does not know about httpOption). If it is empty, then we just leave it as it is.
2. Accordingly, we cannot add Validate for this field like [this](https://github.com/knative/networking/pull/306/files#r544514788). Maybe we just completely drop the Validate function.
3. We should drop the "Disabled" I think as it will involve the problem about how to handle HTTP01 challenge https://github.com/knative/networking/pull/306/files#r544360203. (Sorry about back-and-forth for this part).

Would you mind modifying the PR?

**Comment by arghya88** [comment]
@ZhiminXiang Yes I will modify the PR accordingly
