### ISSUE TITLE
[HTTP Option support] Support HTTP option in net-istio controller

### ISSUE THREAD

**Issue by ZhiminXiang** [knative/networking#302]
After `httpOption` is added into Kingress spec, and is set by Route controller, net-istio controller could start reading the httpOption from the Kingress spec field instead of `config-network` ConfigMap directly.

**Comment by ZhiminXiang** [comment]
Thanks @arghya88 for picking it up. So FYI, before implementing the feature in this issue, we need to ensure that https://github.com/knative/networking/issues/297 and https://github.com/knative/networking/issues/299 are implemented first.

**Comment by arghya88** [comment]
@ZhiminXiang Ah I missed that.I will pick one of those first.

**Comment by ZhiminXiang** [comment]
This issue has been fixed by https://github.com/knative-sandbox/net-istio/pull/658
