### ISSUE TITLE
[HTTP Option support] Support HTTP option in net-contour controller

### ISSUE THREAD

**Issue by ZhiminXiang** [knative/networking#303]
After HTTP option is added into Kingress spec, we can start the implementation of it within net-contour controller in order to integrate with Contour.

**Comment by dprotaso** [comment]
Relevant Doc:
https://docs.google.com/document/d/1dZfHkQORpGvo_Z9hJHWIdq6aTOO8pVP9XFuST1O8h4E/edit#heading=h.n8a530nnrb
