### ISSUE TITLE
net-* should have consistent naming 

### ISSUE THREAD

**Issue by dprotaso** [knative/networking#448]
Going to follow the convention 

`net-[component]-[component_type]` - ie. `net-certmanager-webhook`

- [x] https://github.com/knative-sandbox/net-certmanager/pull/240
- [x] https://github.com/knative-sandbox/net-certmanager/pull/241
- [x] https://github.com/knative-sandbox/net-http01/pull/232
- [x] https://github.com/knative-sandbox/net-istio/pull/683
  - [x] https://github.com/knative-sandbox/net-istio/pull/693
  - [x] https://github.com/knative-sandbox/net-istio/pull/686
- [x] net-ingressv2 - no changes
- [ ] https://github.com/knative-sandbox/net-kourier/pull/555
- [x] https://github.com/knative-sandbox/net-contour/pull/526

Downstream changes
- [x] https://github.com/knative/operator/pull/669
- [x] https://github.com/knative/serving/pull/11551
- [x] https://github.com/knative/serving/pull/11559
- [x] https://github.com/knative/serving/pull/11560

**Comment by nak3** [comment]
https://github.com/knative-sandbox/net-kourier/pull/555 was done. I think this could be closed?
