### ISSUE TITLE
Knative istio client ip is not working

### ISSUE THREAD

**Issue by cinaradem** [knative/networking#499]
Hi,
I am using istio in knative. Since the client ip did not come, I activated the reverse-prox. I added envoyfilter. but I get "upstream connect error or disconnect/reset before headers. reset reason: connection termination" error in services on knative.
if it's not knative service I can access it.

**virtualservice**

------------------------

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-entry-route
  namespace: default
spec:
  gateways:
    - knative-serving/knative-ingress-gateway
  hosts:
    - "test.net"
  http:
    - match:
        - uri:
            prefix: /test/ #working
      rewrite:
        uri: /
      route:
        - destination:
            host: user-api.test.svc.cluster.local
            port:
              number: 80
    - match:
        - uri:
            prefix: /user/ #not working
      route:
        - destination:
            host: istio-ingressgateway.istio-system.svc.cluster.local
            port:
              number: 80
          weight: 100
      rewrite:
        authority: user-api.poker-test.k8s.test.net
        uri: /

**EnvoyFilter**

--------------------

apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: proxy-protocol
  namespace: istio-system
spec:
  configPatches:
    - applyTo: LISTENER
      patch:
        operation: MERGE
        value:
          listener_filters:
            - name: envoy.listener.proxy_protocol
            - name: envoy.listener.tls_inspector
  workloadSelector:
    labels:
      istio: ingressgateway

**service load balancer**

-----------------------------

annotations:
    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: 'true'
externalTrafficPolicy: Local

**Comment by nak3** [comment]
Hi @cinaradem Thank you for the report.
But could you please open the issue on net-istio https://github.com/knative-sandbox/net-istio/ repo?
Also, it would be great if you could use the [Markdown format](https://guides.github.com/features/mastering-markdown/)  for the report. It is a little bit difficult to read without the format :sweat_drops:

**Comment by cinaradem** [comment]
Moved Issue https://github.com/knative-sandbox/net-istio/issues/753
