### ISSUE TITLE
Adopt apps.kubernetes.io labels across networking repos

### ISSUE THREAD

**Issue by dprotaso** [knative/networking#552]
Context: https://github.com/knative/community/issues/667
Serving PR:  https://github.com/knative/serving/issues/11617

**Comment by psschwei** [comment]
This seems like a good Friday project...
/assign

**Comment by psschwei** [comment]
All PRs have merged, so @dprotaso think you can close this

**Comment by dprotaso** [comment]
Awesome thanks for the help
