### ISSUE TITLE
Minor formatting issues

### ISSUE THREAD

**Issue by carlisia** [knative/networking#628]
- [unused parameter: 'req' - test/test_images/httpproxy](https://github.com/knative/networking/blob/9ba6cf46d6dc6b14b0ef07979410d67db2e0e8b8/test/test_images/httpproxy/httpproxy.go#L75-L78)

- Need to s/print/printf so the `port` variable can be printed in the right position

    - [test/test_images/retry/main.go#L44](https://github.com/knative/networking/blob/9ba6cf46d6dc6b14b0ef07979410d67db2e0e8b8/test/test_images/retry/main.go#L44)

    - [test/test_images/runtime/main.go#L523](https://github.com/knative/networking/blob/9ba6cf46d6dc6b14b0ef07979410d67db2e0e8b8/test/test_images/runtime/main.go#L52)

    - [test/test_images/timeout/timeout.go#L57](https://github.com/knative/networking/blob/9ba6cf46d6dc6b14b0ef07979410d67db2e0e8b8/test/test_images/timeout/timeout.go#L57-L58)

    - [test/test_images/wsserver/echo.go#L91](https://github.com/knative/networking/blob/9ba6cf46d6dc6b14b0ef07979410d67db2e0e8b8/test/test_images/wsserver/echo.go#L91)

**Comment by nak3** [comment]
Hmm... Actually I think these are not issue and we don't need to fix them.
