### ISSUE TITLE
Visibility test (proxy image) fails with KinD 0.12.0 + k8s 1.23.x due to DNS issue

### ISSUE THREAD

**Issue by nak3** [knative/networking#660]
When trying to upgrade KinD to 0.12.0, k8s 1.23.x always fails with the following error:

https://github.com/knative-sandbox/net-contour/actions/runs/2164723487
https://github.com/knative-sandbox/net-kourier/actions/runs/2164695709

```
              lookup ingress-conformance-visibility-path-ijgjgogt.serving-tests.svc.c2164695709.local on 10.96.0.10:53: server misbehaving
```

For now, the issue happens as:
- All k8s 1.23.x fails with KinD 0.12.0.
- All net-* repo fails with k8s 1.23.x + KinD 0.12.0.
- All k8s 1.23.x does NOT fail with KinD 0.11.1.

**Comment by csantanapr** [comment]
Could you open an issue in kind git repo with our observations to see if they have any insight in terms of dns and 1.23 in new kind 0.12?

**Comment by nak3** [comment]
Luckily I could solve the problem. (Please refer to the linked PRs.) Closing this issue.
