### ISSUE TITLE
Add comment and validation about current unsupported configuration

### ISSUE THREAD

**Issue by nak3** [knative/networking#848]
`dataplane-trust` and `controlplane-trust` have many options but most of them are not supported. (And IIUC it will not supported in the near feature.)

https://github.com/knative/networking/blob/964322cb1662c5fb25a893f9503c9e012bff05dc/config/config-network.yaml#L183-L206

The comment and validation should be added to avoid confusion.

**Comment by nak3** [comment]
ref https://github.com/knative/serving/issues/13968

**Comment by ReToCode** [comment]
I think this will be resolved with https://github.com/knative/serving/issues/14368, right? The idea is, that we'll only add options if we are really supporting them.

**Comment by nak3** [comment]
Yes, that's right. Closing as https://github.com/knative/serving/issues/14368 can be tracked.
