### ISSUE TITLE
Clean up old secret keys

### ISSUE THREAD

**Issue by nak3** [knative/networking#864]
Since https://github.com/knative/serving/pull/13388 adopted the new keys, most probably it is alright to delete the old keys:

https://github.com/knative/networking/blob/7f9a4a844b37f77565a9ad12cf3b9a45a625e970/pkg/certificates/constants.go#L38-L44

Having both old keys and new keys may introduce a bug like https://github.com/knative/serving/issues/14407 and https://github.com/knative/networking/pull/863 is going to adopt the fix in new keys only.

**Comment by ReToCode** [comment]
I'm adding this to the encryption project. Let's check after we finish the feature, what we can safely drop. I assume there is more of the deprecated stuff that we then can drop.
