### ISSUE TITLE
Intermittent 502s during "visibility/split"

### ISSUE THREAD

**Issue by mattmoor** [knative/networking#87]
I was originally tracking this in https://github.com/knative-sandbox/net-contour/issues/189, but have also seen this in [net-istio](https://prow.knative.dev/view/gcs/knative-prow/logs/ci-knative-sandbox-net-istio-continuous/1293474551715336193) and [net-kourier](https://prow.knative.dev/view/gcs/knative-prow/logs/ci-knative-sandbox-net-kourier-continuous/1293703182970523648).

They basically all fail on a DNS lookup (`:53` is DNS):

```
    util.go:860: Error meeting response expectations: got unexpected status: 502, expected map[200:{}]
    util.go:860: HTTP/1.1 502 Bad Gateway
        Content-Length: 164
        Content-Type: text/plain; charset=utf-8
        Date: Wed, 12 Aug 2020 09:37:18 GMT
        Server: istio-envoy
        X-Content-Type-Options: nosniff
        X-Envoy-Upstream-Service-Time: 8
        
        dial tcp: lookup ingress-conformance-visibility-split-pxtddfbt.serving-tests.svc.cluster.local on 10.11.240.10:53: dial udp 10.11.240.10:53: operation was canceled
```

cc @tcnghia

**Comment by mattmoor** [comment]
@tcnghia are you taking this?

**Comment by mattmoor** [comment]
Hit 2 more of these in net-contour last night.

**Comment by tcnghia** [comment]
/assign @tcnghia 

Cherry picking into https://github.com/knative/test-infra/pull/2361
