### ISSUE TITLE
conformance test for omitted timeout

### ISSUE THREAD

**Issue by mattmoor** [knative/networking#91]
cc @tcnghia @richterdavid 

/kind good-first-issue
/kind cleanup

**Comment by mattmoor** [comment]
We might also consider deprecating this field and removing the other tests, which occasionally flake for me.

**Comment by mattmoor** [comment]
cc @nak3 

Want to knock these off too? 😇

**Comment by nak3** [comment]
Sure, I take it :smile_cat:
