### ISSUE TITLE
Deprecate retry

### ISSUE THREAD

**Issue by mattmoor** [knative/networking#92]
I believe that route has stopped specifying this, but we still have tests for it which run a pretty sizable matrix of now unexercised functionality.

Consider deprecating the field, and removing the conformance tests.

/assign @tcnghia 
/kind cleanup

**Comment by mattmoor** [comment]
cc @nak3 @ZhiminXiang

**Comment by nak3** [comment]
/assign

I will clean up it.

**Comment by mattmoor** [comment]
Awesome, thanks!
